version: '3.5'

services:
  app:
    build: .
    container_name: practice-sales-backend
    depends_on: 
      - db
    environment:
      DB_HOST: postgres # Override local env
    networks:
      - postgres_network
    ports:
      - "3000:3000"
    restart: on-failure
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "0000"
    hostname: postgres
    networks:
      - postgres_network
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./models/db/data.sql:/docker-entrypoint-initdb.d/data.sql:ro

networks:
  postgres_network:
    external: false
    name: postgres_network